Add validator for emails with TLDs
noahsalvi/svelte-use-form pull request #61
Opened 2023-08-28 19:35 UTC by keehun

The `email` validator currently present in `svelte-use-form` doesn't force a TLD (as discussed https://github.com/noahsalvi/svelte-use-form/issues/59).

This PR adds an `email_with_tld` validator which is very similar to the `email` validator but forces a TLD component to the email host name.

2023-08-28 19:36 UTC, keehun commented
@noahsalvi do you have any CICD that I should run?

2023-08-31 13:06 UTC, noahsalvi requested changes
Awesome, thank you for the PR!

2023-08-31 13:06 UTC, noahsalvi commented on tests/email-validator.spec.ts
> +for (const address of valid_emails) {
Would it be possible to nest these tests into a single one? I believe Playwright's error messages already suffice.

2023-08-31 13:06 UTC, noahsalvi commented on README.md
> +- `email_with_tld`
I would prefer camel case

2023-08-31 13:07 UTC, noahsalvi commented on README.md
> +- `email_with_tld`
Likewise for the other variables except if you have a reason as to why you chose it.

2023-09-09 01:15 UTC, keehun commented
@noahsalvi do you have any documentation on getting dev environment set up for testing? I swear before I went on vacation, `npm run tests` was working fine, but now it gives me errors like:
```
[WebServer] error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/[...]/svelte-use-form/.svelte-kit/output/server/index.js' imported from /Users/[...]/svelte-use-form/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
```

Not sure exactly what changed or what the issue is. I wonder if specifying `next` for `@sveltejs/kit` is contributing to instability. What version do you have installed locally?

2023-09-12 10:42 UTC, noahsalvi commented
I just found out what caused this! I recently separated the build step from the test call meaning that you now need to run `npm run build` before calling `npm run test`... 

I changed this so that when adding tests, you wouldn't need to repeatedly build the project. Is this bad DX?

2023-09-13 21:39 UTC, keehun commented
🤦 Of course. Now that you mention it, I had figured that out prior to my vacation but forgot afterwards.

It'd be better if the error message said to go build instead of the more obscure message it shows now. Not sure if it's something that you can influence.

Does `npm run build` actually build if none of the source has changed? If so, then I don't think forcing a build prior to running tests would hurt (and would be a good idea). If NPM is not smart enough, then I would say what you have now is good.

2023-09-17 14:43 UTC, keehun commented
After spending a few more minutes on this, I think because the build time is so quick for this package, you should consider always building before tests. Changing something about the page (like `id` of an element) used for tests will cause tests to fail, and it's unclear why it's failing until you realize you need to rebuild.

2023-09-17 14:44 UTC, keehun commented
I've made all the changes. Should be ready for final review/tests!

2023-09-17 15:35 UTC, merged